name: build-and-push-image

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'Dockerfile'
      - 'config/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build Docker image
      run: docker build -t lcwllmr/pyjlab:latest .
